sudo: false

language: generic

before_install:
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
  - openssl aes-256-cbc -K $encrypted_a2d2f610dfff_key -iv $encrypted_a2d2f610dfff_iv -in deploy_key.enc -out deploy_key -d
  - git clone https://github.com/langue-festival/langue-festival.github.io.git deploy

cache:
  directories:
    - elm/elm-stuff
    - node_modules
    - sysconfcpus

script:
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 make

after_success:
  - bash deploy.sh

branches:
  only:
    - master

env:
  global:
    - COMMIT_AUTHOR_EMAIL=emiliano.bovetti@gmail.com

addons:
  apt:
    update: true
