sudo: false

language: generic

cache: yarn

before_install:
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

cache:
  directories:
    - elm/elm-stuff
    - sysconfcpus

script:
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 make

branches:
  only:
    - master

env:
  global:
    - ENCRYPTION_LABEL: "a2d2f610dfff"
    - COMMIT_AUTHOR_EMAIL: "emiliano.bovetti@gmail.com"
